verbosity = 0

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"
offset_encoding = "utf-8"

[language.rust.initialization_options]
offsetEncoding = ["utf-8"]
formatTool = "rustfmt"

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_flags.txt", "compile_commands.json"]
command = "clangd"
offset_encoding = "utf-8"

[language.c_cpp.initialization_options]
offsetEncoding = ["utf-8"]
formatTool = "clang-format"
